sudo: required

language: javascript

services:
  - docker

before_install:
  - docker login --email=$DOCKER_EMAIL --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  - docker build -t $DOCKER_IMAGE_NAME .

script:
  - docker run -e TEST=true -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN -e TELEGRAM_ANALYTICS=$TELEGRAM_ANALYTICS $DOCKER_IMAGE_NAME
  - docker push $DOCKER_IMAGE_NAME

env:
 - DOCKER_IMAGE_NAME=georgerappel/godzilla-telegram-bot
